apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    tier: frontend
  clusterIP: 10.99.132.221
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3070
  type: LoadBalancer

